# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c8f472b4971c0d2dad8e8922f3295fbbf5f90f3c47a93048076d663c6360ba9df2e667dddab58b3784ab405aab9af8d5d8209479b36fa5cec69667e430874b

test:
  secret_key_base: 2907edb539ed935c83450135dca9c19dc5634d4c5546a4812297946a6b6aa3f113a9d0a5bc226783cf8437c9102021583af9efb38500dc91ac416acf801397ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
